Butchers/Controllers/Admin/OrderAdminController.cs
using Butchers.Data;
using Butchers.Data.BEANS;
using Butchers.Services.IService;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Butchers.Controllers.Admin
{
    [Authorize(Roles = "Admin, Manager, Staff, Customer")]
    public class OrderAdminController : ApplicationController
    {
        public OrderAdminController()
        {

        }

        // OrderAdmin/AddPromoCode
        [HttpGet]
        [Authorize(Roles = "Manager")]
        public ActionResult AddPromoCode()
        {
            // Returns the addPromoCode view
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Manager")]
        public ActionResult AddPromoCode(PromoCode pCode)
        {
            try
            {
                // Adds the promo code
                _orderService.AddPromoCode(pCode);

                // Returns the user to the promo code list
                return RedirectToAction("PromoCode", new { controller = "Order" });
            }
            catch
            {
                // This currently redirects the user to the addPromoCode view
                // ** This would benefit from some error recognition by using an error page or toaster notifications
                return View();
            }
        }

        // OrderAdmin/EditPromoCode/1
        [HttpGet]
        [Authorize(Roles = "Manager")]
        public ActionResult EditPromoCode(string id)
        {
            // The edit promocode view is returned matching the id (code) of the selected promo code
            return View(_orderService.GetBEANPromoCode(id));
        }

        [HttpPost]
        [Authorize(Roles = "Manager")]
        public ActionResult EditPromoCode(string id, PromoCodeBEAN codeBEAN)
        {
            try
            {
                // The promo code object is updated...
                PromoCode myPromoCode = new PromoCode
                {
                    Code = codeBEAN.Code,
                    Discount = codeBEAN.Discount,
                    ValidUntil = codeBEAN.ValidUntil
                };

                // ...and the edit method is called upon, updating the existing values with the new ones
                _orderService.EditPromoCode(myPromoCode);
            }
            catch
            {

            }

            // Whether a success or failure, the user is redirected back to the promo code list
            // ** This can be refined with error notifications
            return RedirectToAction("PromoCode", new { controller = "Order" });
        }


        // Cart items are the product items which have been added to the cart
        [HttpGet]
        [Authorize(Roles = "Customer")]
        public ActionResult DeleteCartItem(int id)
        {
            // The delete cart item view is returned to the user matching the item selected for deletion
            return View(_orderService.GetBEANCartItem(id));
        }

        [HttpPost]
        [Authorize(Roles = "Customer")]
        public ActionResult DeleteCartItem(int id, CartItemBEAN CartBEAN)
        {
            try
            {
                CartItem myCartItem = _orderService.GetCartItem(id); // The cart item is selected from the id of the list item which has been chosen

                _orderService.DeleteCartItem(myCartItem); // The delete method is called upon passing the object for deletion
            }
            catch
            {

            }

            // Pass or fail, the user is redirected back to the product item list
            return RedirectToAction("ProductItems", new { controller = "Product" }); // ** This could do with some error notification
        }

        // This replaced AddCartItem as more functionality was needed
        // This takes care of adding product items to a cart
        [HttpGet]
        [Authorize(Roles = "Customer")]
        public ActionResult AddProductToCart(int productItemId, decimal cost, string quantity)
        {
            try
            {
                int cartId;

                // Check to see whether Cart exists
                if (Session["CartId"] == null)
                {
                    Cart cart = new Cart();
                    
                    cartId = _orderService.AddCartAndReturnId(cart); // If the cart doesn't exist, one is created and the AddCartAndReturnId method does what it says

                    Session["CartId"] = cartId; // We use that id to assign the variable to the session
                }
                else
                {
                    cartId = int.Parse(Session["CartId"].ToString()); // If the Cart exists in Session, take the CartId and assign to the variable cartId
                }

                // From the productItem selected, quantity entered and the session, a cartItem is created
                CartItem cartItem = new CartItem
                {
                    CartId = cartId,
                    ProductItemId = productItemId,
                    Quantity = int.Parse(quantity),
                    ItemCostSubtotal = cost
                };

                // This information is passed to the AddCartItem method to add a new cart item
                _orderService.AddCartItem(cartItem);

                // Once these steps have been executed, the user is redirected
                return RedirectToAction("ProductItems", new { controller = "Product" });
            }
            catch(Exception ex)
            {
                Console.Out.WriteLine(ex);

                // ** This would benefit from better error notification
                return RedirectToAction("ProductItems", new { controller = "Product" });
            }
        }

        // SubmitOrder takes the cartItems and a number of other variables and adds them to a customer order
        [HttpGet]
        [Authorize(Roles = "Customer")]
        public ActionResult SubmitOrder(string promoCode, ProductItem item)
        {
            try
            {
                int cartId;

                // Assigns the session's CartId to the variable
                // We assume that one exists otherwise they wouldn't see the options for Submitting an order
                cartId = int.Parse(Session["CartId"].ToString());
                
                Order order = new Order(); // Add an order

                var userID = User.Identity.GetUserId(); // This detects the logged in user's id and assigns it to the variable userId

                // As long as there is a user logged in, the order can be processed, otherwise they are redirected to log in
                // An unauthenticated user shouldn't be able to get to this point anyway, it's just a failsafe
                if (!string.IsNullOrEmpty(userID))
                {
                    order.OrderDate = DateTime.Now; // Today's date
                    order.CustomerNo = userID; // Current Customer
                    order.TotalCost = _orderService.GetCartCost(cartId); // Uses the method which calculates Cart Cost
                    
                    if (promoCode != null && promoCode != "") // This checks to see whether a promo code is being used
                    {
                        decimal currentTotal = order.TotalCost; // Assigns the current total cost and promo code to variables that can be used by the GetCostAfterDiscount method
                        order.PromoCode = promoCode; 
                        
                        order.TotalCostAfterDiscount = _orderService.GetCostAfterDiscount(currentTotal, promoCode); // Uses the method which applies the discount
                        
                        // This is currently used to notify the user that the promo code is invalid
                        if (order.TotalCostAfterDiscount == -1) // -1 is returned if the promo code is invalid
                        {
                            TempData["message"] = "The Promo code you entered is invalid.";

                            // ** This probably needs improving with a more standardised way of giving feedback to the user (toaster, etc)
                            return RedirectToAction("ViewCart", new { controller = "Order" });
                        }
                    }
                    else
                    {
                        order.PromoCode = null; // If there is no promo code entered, don't use one
                        order.TotalCostAfterDiscount = order.TotalCost; // If no promo code, there will be no discount
                    }
                    order.CartId = cartId;
                    
                    int orderNo = _orderService.AddOrderAndReturnId(order); // Using the information above, add an order and return its id (order no) to generate the order details

                    // Automatically set Order Details after the order has been placed.
                    OrderDetails orderDetails = new OrderDetails
                    {
                        OrderNo = orderNo, // Use the order number generated from the add method
                        CollectFrom = order.OrderDate.AddDays(1), // Take tomorrow's date
                        CollectBy = order.OrderDate.AddDays(8) // Take tomorrow's date + 7 days

                        // ** The days for collection could be customised by business preferences when this is implemented
                    };

                    _orderService.AddOrderDetails(orderDetails);
                    
                    IList<CartItemBEAN> items = _orderService.GetCartItemsByCartId(cartId);
                    foreach (var cartItem in items) // Automatically reduce stock when an order is placed by looping through a list of the items in the cart
                    {
                        int id = cartItem.ProductItemId;
                        

Butchers/Controllers/ProductAdminController.cs
using Butchers.Data;
using Butchers.Data.BEANS;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Butchers.Controllers
{
    public class ProductAdminController : ApplicationController
    {
        public ProductAdminController()
        {

        }

        // Meat/AddMeat
        [HttpGet]
        public ActionResult AddMeat()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddMeat(Meat meat)
        {
            try
            {
                _productService.AddMeat(meat);
                return RedirectToAction("Meats", new { controller = "Product" });
            }
            catch
            {
                return View();
            }
        }

        // Meat/EditMeat/1
        [HttpGet]
        public ActionResult EditMeat(int id)
        {
            return View(_productService.GetMeat(id));
        }

        [HttpPost]
        public ActionResult EditMeat(int id, Meat meat)
        {
            try
            {
                _productService.EditMeat(meat);
            }
            catch
            {

            }
            return RedirectToAction("Meats", new { controller = "Product" });
        }

        // Meat/DeleteMeat/1
        [HttpGet]
        public ActionResult DeleteMeat(int id)
        {
            return View(_productService.GetMeat(id));
        }

        [HttpPost]
        public ActionResult DeleteMeat(Meat meat)
        {
            try
            {
                Meat _meat;
                _meat = _productService.GetMeat(meat.Id);
                _productService.DeleteMeat(_meat);
            }
            catch
            {

            }
            return RedirectToAction("Meats", new { controller = "Product" });
        }

        // Product/AddProduct
        [HttpGet]
        public ActionResult AddProduct(string selectedMeat)
        {
            List<SelectListItem> meatList = new List<SelectListItem>();
            foreach(var item in _productService.GetMeats())
            {
                meatList.Add(
                  new SelectListItem()
                  {
                      Text = item.Name,
                      Value = item.Id.ToString(),
                      Selected = (item.Name == (selectedMeat) ? true : false)
                  });
            }
            ViewBag.meatList = meatList;
            return View();
        }

        [HttpPost]
        public ActionResult AddProduct(Product product)
        {
            try
            {
                _productService.AddProduct(product);
                return RedirectToAction("Products", new { controller = "Product" });
            }
            catch
            {
                return View();
            }
        }

        // ProductAdmin/EditProduct/1
        [HttpGet]
        public ActionResult EditProduct(int id){

            return View(_productService.GetProduct(id));

        }

        [HttpPost]
        public ActionResult EditProduct(int id, ProductBEAN product)
        {
            try
            {
                Product myProduct = new Product();

                myProduct.Id = product.Id;
                myProduct.MeatId = product.MeatId;
                myProduct.Name = product.Name;




                _productService.EditProduct(myProduct);

            }
            catch
            {


            }
            return RedirectToAction("Products", new { controller = "Product" });


        }

        // ProductAdmin/DeleteProduct/1
        [HttpGet]
        public ActionResult DeleteProduct(int id)
        {

            return View(_productService.GetProduct(id));

        }

        [HttpPost]
        public ActionResult DeleteProduct (int id, ProductBEAN product)
        {
            try
            {
                Product myProduct = _productService.GetProduct(id);

                _productService.DeleteProduct(myProduct);
            }


            catch
            {

            }
            return RedirectToAction("Products", new { controller = "Product" });
        }

        // ProductItemAdmin/AddProductItem
        [HttpGet]
        public ActionResult AddProductItem(string selectedProduct)
        {
            List<SelectListItem> productList = new List<SelectListItem>();
            foreach (var item in _productService.GetProducts())
            {
                productList.Add(
                    new SelectListItem()
                    {
                        Text = item.Name,
                        Value = item.Id.ToString(),
                        Selected = (item.Name == (selectedProduct) ? true : false)
                    });
            }

            ViewBag.productList = productList;

            return View();
        }

        [HttpPost]
        public ActionResult AddProductItem(ProductItem productItem)
        {
            try
            {
                _productService.AddProductItem(productItem);
                return RedirectToAction("ProductItems", new { controller = "Product" });
            }
            catch
            {
                return View();
            }
        }

        // ProductItemAdmin/EditProductItem/1
        [HttpGet]
        public ActionResult EditProductItem(int id)
        {
            return View(_productService.GetProductItemBEAN(id));
        }

        [HttpPost]
        public ActionResult EditProductItem(int id, ProductItemBEAN productItem)
        {
            try
            {
                ProductItem myProductItem = new ProductItem();

                myProductItem.Id = productItem.Id;
                myProductItem.ProductId = productItem.ProductId;
                myProductItem.Cost = productItem.Cost;
                myProductItem.PerUnit = productItem.PerUnit;
                myProductItem.Discontinued = productItem.Discontinued;

                _productService.EditProductItem(myProductItem);
            }
            catch
            {

            }
            return RedirectToAction("ProductItems", new { controller = "Product" });
        }

        // ProductItemAdmin/DeleteProductItem/1
        [HttpGet]
        public ActionResult DeleteProductItem(int id)
        {
            return View(_productService.GetProductItemBEAN(id));
        }

        [HttpPost]
        public ActionResult DeleteProductItem(int id, ProductItemBEAN productItem)
        {
            try
            {
                ProductItem myProductItem = _productService.GetProductItem(id);
                _productService.DeleteProductItem(myProductItem);
            }
            catch
            {

            }
            return RedirectToAction("ProductItems", new { controller = "Product" });
        }
    }
}

Butchers/Views/Product/ActiveProductItems.cshtml
@model IEnumerable<Butchers.Data.BEANS.ProductItemBEAN>

@* Setting the viewbag here means that this can be called in the partial view, meaning the name can be changed depending on the page. *@

@if (User.IsInRole("Customer") && (!User.IsInRole("Manager") || !User.IsInRole("Staff")))
{
    ViewBag.Title = "Product Items";
}
else if (User.IsInRole("Manager") || User.IsInRole("Staff"))
{
    ViewBag.Title = "Product Items - Active";
}

@* Renders the partial view which uses a standard layout for product items *@
@* This allows for the reuse of code *@
@{
    Html.RenderPartial("_ProductItems");
}

Butchers/Views/Product/DiscontinuedProductItems.cshtml
@model IEnumerable<Butchers.Data.BEANS.ProductItemBEAN>

@* Setting the viewbag here means that this can be called in the partial view, meaning the name can be changed depending on the page. *@
@{
    ViewBag.Title = "Product Items - Discontinued";
}

@* Renders the partial view which uses a standard layout for product items *@
@* This allows for the reuse of code *@
@{
    Html.RenderPartial("_ProductItems");
}

Butchers/Views/Product/Meats.cshtml
@model IEnumerable<Butchers.Data.BEANS.MeatBEAN>

@{
    ViewBag.Title = "Meats";
}

<div class="row">
    <div class="col-md-10">
        <h2>@ViewBag.Title</h2>
    </div>
    <div class="col-md-2">
        <button class="btn btn-info btn-header" data-toggle="collapse" onclick="location.href='@Url.Action("AddMeat", "ProductAdmin")'"><i class="fas fa-plus"></i></button>
    </div>
</div>
<hr />

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-3">
            <div class="card mb-3" style="width: 100%;">
                <div class="row">
                    <div class="col-md-12">
                        @* Placeholder to be updated once centralised storage is implemented *@
                        <img src="https://images.pexels.com/photos/65175/pexels-photo-65175.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" style="width: 100%;">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <h3 style="text-align: center;">@Html.DisplayFor(modelItem => item.Name)</h3>
                    </div>
                </div>
                <div class="container">
                    <div class="row">

                        <div class="col-xs-6 col-sm-6 col-md-6" style="padding: 0px;">
                            <button class="btn btn-info" style="width: 100%;" onclick="location.href='@Url.Action("EditMeat", new { id = item.MeatId, Controller = "ProductAdmin" })'"><i class="fas fa-edit"></i></button>
                        </div>

                        <div class="col-xs-6 col-sm-6 col-md-6" style="padding: 0px;">
                            <button class="btn btn-info" style="width: 100%;" onclick="location.href='@Url.Action("DeleteMeat", new { id = item.MeatId, Controller = "ProductAdmin" })'"><i class="fas fa-trash-alt"></i></button>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    }
</div>

Butchers/Views/Product/ProductItems.cshtml
@model IEnumerable<Butchers.Data.BEANS.ProductItemBEAN>

@{
    ViewBag.Title = "ProductItems";
}

<div class="row">
    <div class="col-md-11">
        <h2>Product Items</h2>
    </div>
    <div class="col-md-1">
        @if (User.IsInRole("Admin") || User.IsInRole("Manager"))
        {
        <button class="btn btn-info" style="width: 100%;" onclick="location.href='@Url.Action("AddProductItem", "ProductAdmin")'"><i class="fas fa-plus"></i></button>
        }
    </div>
</div>
<hr />

<div class="row">

    @foreach (var item in Model)
    {
        <div class="col-md-3">
            <div class="container">
                <div class="row">
                    <div class="col-md-12" style="padding: 0px;">
                        <img src="https://placeimg.com/640/300/animals/grayscale" style="width: 100%;">
                    </div>
                </div>
                    <div class="row">
                        <h3>@Html.DisplayFor(modelItem => item.Product)</h3>
                    </div>
                    <div class="row">
                        <p>£@Html.DisplayFor(modelItem => item.Cost) per @Html.DisplayFor(modelItem => item.MeasurementName)</p>
                    </div>
                    <div class="row">
                        @if (User.IsInRole("Admin") || User.IsInRole("Manager"))
                        {
                            <div class="col-md-6" style="padding: 0px;">
                                <button class="btn btn-info" style="width: 100%;" onclick="location.href='@Url.Action("EditProductItem", new { id = item.ProductItemId, product = item.ProductId, measurement = item.MeasurementId, Controller = "ProductAdmin" })'"><i class="fas fa-edit"></i></button>
                            </div>
                            <div class="col-md-6" style="padding: 0px;">
                                <button class="btn btn-info" style="width: 100%;" onclick="location.href='@Url.Action("DeleteProductItem", new { id = item.ProductItemId, Controller = "ProductAdmin" })'"><i class="fas fa-trash-alt"></i></button>
                            </div>
                        }
                        else
                        {
                            if (User.IsInRole("Customer"))
                            {
                                <div class="col-md-12" style="padding: 0px;">

                                    @using (Html.BeginForm("AddProductToCart", "OrderAdmin", FormMethod.Get))
                                    {
                                        <div class="container">
                                            <div class="row">
                                                <div class="col-md-10" style="padding: 0px;">
                                                    @Html.DropDownList("quantity", new SelectList(Enumerable.Range(0, 11)), new { @class = "form-control" })
                                                </div>
                                                <div class="col-md-2" style="padding: 0px;">
                                                    <button type="submit" class="btn btn-info" style="width: 100%;"><i class="fas fa-cart-plus"></i></button>
                                                </div>

                                                <input type="hidden" name="productItemId" id="productItemId" value="@item.ProductItemId" />
                                                <input type="hidden" name="cost" id="cost" value="@item.Cost" />

                                            </div>
                                        </div>
                                        @*<input type="submit" value="Add to card" />*@
                                    }

                                    @*<button class="btn btn-info" style="width: 80%;" onclick="location.href='@Url.Action("AddProductToCart", new { productItemId = , cost = , Controller = "OrderAdmin" })'"><i class="fas fa-cart-plus"></i></button>*@

                                </div>
                            }
                        }
                    </div>
                    <hr />
                    <br />
                </div>

        </div>
    }

</div>

Butchers/Views/Product/Products.cshtml
@model IEnumerable<Butchers.Data.BEANS.ProductBEAN>

@{
    ViewBag.Title = "Products";
}

<div class="row">
    <div class="col-md-10">
        <h2>Products</h2>
    </div>
    <div class="col-md-2">
        <button class="btn btn-info btn-header" onclick="location.href='@Url.Action("AddProduct", "ProductAdmin")'"><i class="fas fa-plus"></i></button>
    </div>
</div>
<hr />
<div class="row">

    @foreach (var item in Model){

        <div class="col-md-3">
            <div class="card mb-3" style="width: 100%;">
                <div class="row">
                    <div class="col-md-12">
                        <img src="https://images.pexels.com/photos/266905/pexels-photo-266905.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" style="width: 100%;">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12" style="text-align: center;">
                        <h3>@Html.DisplayFor(modelItem => item.Name)</h3>
                    </div>
                </div>

                @if (User.IsInRole("Admin") || User.IsInRole("Manager"))
                {
                    <div class="container">
                        <div class="row">

                            <div class="col-md-6" style="padding: 0px;">
                                <button class="btn btn-info" style="width: 100%;" onclick="location.href='@Url.Action("EditProduct", new { id = item.ProductId, meatId = item.MeatId, Controller = "ProductAdmin" })'"><i class="fas fa-edit"></i></button>
                            </div>

                            <div class="col-md-6" style="padding: 0px;">
                                <button class="btn btn-info" style="width: 100%;" onclick="location.href='@Url.Action("DeleteProduct", new { id = item.ProductId, Controller = "ProductAdmin" })'"><i class="fas fa-trash-alt"></i></button>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    }

</div>

Butchers/Views/Product/_LowStock.cshtml
@model IEnumerable<Butchers.Data.BEANS.ProductItemBEAN>

<div class="row">

@if (Model.Count() > 0)
{
        foreach (var item in Model)
        {
            <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-12">
                            <img src="https://baconmockup.com/300/200" style="width: 100%;">
                        </div>
                    </div>
                    <div class="row" style="text-align: center; padding-top: 10px;">
                        <div class="col-md-12">
                            <h3>@Html.DisplayFor(modelItem => item.Product)</h3>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12" style="text-align: center;">
                            <p>£@Html.DisplayFor(modelItem => item.Cost) per @Html.DisplayFor(modelItem => item.MeasurementName)</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            @if (item.StockQty > 10)
                            {
                                ViewBag.alertStatus = "success";
                                ViewBag.icon = "check-circle";
                                ViewBag.stockStatus = "In Stock";
                            }
                            else if (item.StockQty < 11 && item.StockQty > 0)
                            {
                                ViewBag.alertStatus = "warning";
                                ViewBag.icon = "exclamation-circle";
                                ViewBag.stockStatus = @Html.DisplayFor(modelItem => item.StockQty) + " Remaining!";
                            }
                            else if (item.StockQty == 0)
                            {
                                ViewBag.alertStatus = "danger";
                                ViewBag.icon = "times-circle";
                                ViewBag.stockStatus = "Out of Stock";
                            }

                            <div class="row">
                                <div class="col-md-12" style="text-align: center;">
                                    <div class="alert alert-@ViewBag.alertStatus" style="width: 100%; margin-bottom: 0px;">
                                        <i class="fas fa-@ViewBag.icon"></i>&nbsp; @ViewBag.stockStatus
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <button class="btn btn-info" data-toggle="collapse" data-target="#@item.ProductItemId" style="width: 100%;" @ViewBag.Disabled><i class="fas fa-plus"></i>&nbsp; Add Stock</button>
                                </div>
                            </div>
                        </div>
                    </div>

                <div id="@item.ProductItemId" class="collapse">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12" style="padding: 0px;">
                                <div class="card text-white mb-3" style="width: 100%;">
                                    <div class="card-body">
                                        @using (Html.BeginForm("UpdateStock", "ProductAdmin", FormMethod.Get))
                                        {
                                            <div class="container">
                                                <div class="row">
                                                    <div class="col-md-9" style="padding: 0px;">
                                                        @Html.DropDownList("quantity", new SelectList(Enumerable.Range(0, 11)), new { @class = "form-control" })
                                                    </div>

                                                    <div class="col-md-3" style="padding: 0px;">
                                                        <button type="submit" class="btn btn-info" style="width: 100%;"><i class="fas fa-plus"></i></button>
                                                    </div>

                                                    <input type="hidden" name="productItemId" id="productItemId" value="@item.ProductItemId" />
                                                    <input type="hidden" name="stockQty" id="stockQty" value="@item.StockQty" />
                                                </div>
                                            </div>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <hr />
                </div>
    }
}
else
{
    <div class="col-md-12">
        <div class="alert alert-success">
            <strong>Phew!</strong> All of your active items are in stock!
        </div>
    </div>
}
</div>