Butchers/Controllers/Admin/CompanyAdminController.cs
using Butchers.Data;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Butchers.Controllers.Admin
{
    [Authorize(Roles = "Manager, Staff")]
    public class CompanyAdminController : ApplicationController
    {
        public CompanyAdminController()
        {

        }

        [HttpGet]
        [Authorize(Roles = "Staff, Manager")]
        public ActionResult AddMessage(string subject, string body)
        {
            try
            {
                var uid = User.Identity.GetUserName(); // Gets the logged in user's name and assigns it to the variable uid
                Message message = new Message
                {
                    MessageSubject = subject,
                    MessageBody = body,
                    MessageAuthor = uid, // author is set to the logged in user
                    MessageDate = DateTime.Now // message date is set to today's date
                };

                _companyService.AddMessage(message);

                return RedirectToAction("Dashboard", new { controller = "Home" }); // Redirects the user to their dashboard.
            }
            catch
            {
                return View(); // ** This should be changed at some point to show custom validation or error feedback
            }
        }
    }
}

Butchers/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Butchers.Controllers
{
    [Authorize(Roles = "Admin, Manager, Staff, Customer")]
    public class CompanyController : ApplicationController
    {
        public CompanyController()
        {

        }

        // PromoCodes
        [Authorize(Roles = ("Customer"))]
        public ActionResult _Message()
        {
            return PartialView(_companyService.GetMessages()); // Displays a list of messages as a partial view in the customer dashboard
        }
    }
}

Butchers/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Butchers.Data;
using Butchers.Services.Service;

namespace Butchers.Controllers
{
    [AllowAnonymous]
    public class HomeController : Controller
    {
        public ProductService _productService;
        public OrderService _orderService;

        public HomeController()
        {
            _productService = new ProductService();
            _orderService = new OrderService();
        }

        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated) // Checks whether the user is logged in or not
            {
                return RedirectToAction("Dashboard", "Home"); // If the user is logged in, redirect them to the dashboard instead of the index page
            }
            else
            {
                return View(); // If the user isn't logged in, redirect them to the index page as normal
            }
        }

        public ActionResult RegisterSuccess()
        {
            ViewBag.Message = "Registration Successful. Please log in."; // This is displayed after a user registers and is logged out

            return View();
        }

        [Authorize(Roles = "Admin, Manager, Staff, Customer")]
        public ActionResult Dashboard()
        {
            // Order Statistics - the results of these methods are assigned to viewbags and called upon in the razor views
            ViewBag.CountPromoCodes = _orderService.CountPromoCodes();
            ViewBag.CountCarts = _orderService.CountCarts();
            ViewBag.CountOrders = _orderService.CountOrders();
            ViewBag.countOrdersCollected = _orderService.countOrdersCollected();
            ViewBag.countOrdersCancelled = _orderService.countOrdersCancelled();

            // Product Statistics - the results of these methods are assigned to viewbags and called upon in the razor views
            ViewBag.CountMeats = _productService.CountMeats();
            ViewBag.CountProducts = _productService.CountProducts();
            ViewBag.CountProductItems = _productService.CountProductItems();

            return View();
        }
    }
}

Butchers/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Butchers/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Butchers/Views/Home/Dashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
}

<div class="row">
    <div class="col-md-12">
        <h1>Welcome back to Meat Management</h1>
        <p class="lead">Take a look around and don't hesitate to contact us</a> if you have any questions!</p>
        <hr class="my-4">
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        @if (User.IsInRole("Staff") || User.IsInRole("Manager"))
        {
            using (Html.BeginForm("AddMessage", "CompanyAdmin", FormMethod.Get))
            {
                <div class="card mb-3" style="width: 100%;">
                    <div class="card-header text-white bg-info ">Message</div>
                    <div class="card-body">
                            <div class="container" style="padding-bottom: 10px; padding-top: 10px;">
                                <div class="row">
                                    <div class="col-md-12">
                                        <h2>Post a Message</h2>
                                        <hr />
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <label>Subject</label>
                                        @Html.TextBox("subject", null, new { @class = "form-control", placeholder = "Enter a Subject", maxlength = 51 })
                                    </div>
                                </div>
                                <br />
                                <div class="row">
                                    <div class="col-md-12">
                                        <label>Message</label>
                                        @Html.TextArea("body", null, new { @class = "form-control", placeholder = "Enter a Message", maxlength = 301 })
                                    </div>
                                </div>
                                <br />
                                <div class="row">
                                    <div class="col-md-6">
                                        <button type="submit" class="btn btn-info" style="width: 100%;"><i class="fas fa-plus"></i>&nbsp;&nbsp; Post Message</button>
                                    </div>
                                    <div class="col-md-6">

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <br />
            }
        }
        else if (User.IsInRole("Admin"))
        {
            <div class="card mb-3" style="width: 100%;">
                <div class="card-header text-white bg-info ">Product Statistics</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-2">@ViewBag.CountMeats</div>
                        <div class="col-md-10">Total No. of Meats</div>
                    </div>
                    <div class="row">
                        <div class="col-md-2">@ViewBag.CountProducts</div>
                        <div class="col-md-10">Total No. of Products</div>
                    </div>
                    <div class="row">
                        <div class="col-md-2">@ViewBag.CountProductItems</div>
                        <div class="col-md-10">Total No. of Product Items</div>
                    </div>
                </div>
            </div>
        }
        else if (User.IsInRole("Customer"))
        {
            <div class="card mb-3" style="width: 100%;">
                <div class="card-header text-white bg-info ">Messages</div>
                <div class="card-body">
                    @{
                        Html.RenderAction("_Message", "Company");
                    }
                </div>
            </div>
        }
        else
        {

        }
    </div>
    <div class="col-md-6">
            @if (User.IsInRole("Staff") || User.IsInRole("Manager"))
            {
                <div class="card mb-3" style="width: 100%;">
                    <div class="card-header text-white bg-info ">Stock Alert</div>
                    <div class="card-body">
                        @{
                            Html.RenderAction("_LowStock", "Product");
                        }
                    </div>
                </div>
            }
            else if (User.IsInRole("Admin"))
            {
                <div class="card mb-3" style="width: 100%;">
                    <div class="card-header text-white bg-info ">Order Statistics</div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-2">@ViewBag.CountPromoCodes</div>
                            <div class="col-md-10">Total No. of Promo Codes</div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">@ViewBag.CountCarts</div>
                            <div class="col-md-10">Total No. of Carts</div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">@ViewBag.CountOrders</div>
                            <div class="col-md-10">Total No. of Reservations</div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">@ViewBag.countOrderscollected</div>
                            <div class="col-md-10">Total No. of Reservations (Collected)</div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">@ViewBag.countOrdersCancelled</div>
                            <div class="col-md-10">Total No. of Reservations (Cancelled)</div>
                        </div>
                    </div>
                </div>
            }
            else if (User.IsInRole("Customer"))
            {
                <div class="card mb-3" style="width: 100%;">
                    <div class="card-header text-white bg-info ">What's Hot!</div>
                    <div class="card-body">
                        @{
                            Html.RenderAction("_TopStock", "Product");
                        }
                    </div>
                </div>
            }
            else
            {

            }
    </div>
</div>

Butchers/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1 class="display-3">Meat Management</h1>
    <p class="lead">Delivering high quality sales and stock management solutions to your local butchers.</p>
    <hr class="my-4">
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Stock Control</h2>
        <p>
            Our solution allows you to easily keep track of your stock. With options to add and remove stock manaually, much of the management is automated, saving you valuable time to serve your customers!
        </p>
    </div>
    <div class="col-md-4">
        <h2>Reservations</h2>
        <p>Reduce the amount of time you spend managing reservations on social media or over the phone by allowing customers to reserve your products through your site.</p>
    </div>
    <div class="col-md-4">
        <h2>User Friendly</h2>
        <p>We have made this service with you in mind. Manage your stock, your reservations and your business easily with this service. If you have any suggestions, however, we're all ears! Contact us here</a>!</p>
    </div>
</div>

Butchers/Views/Home/RegisterSuccess.cshtml
@{
    ViewBag.Title = "Register Success";
}

<h2>Registration Successful!</h2>

<div class="alert alert-dismissible alert-success">
    <strong>@ViewBag.Message</strong> <a href="@Url.Action("Login", "Account")" class="alert-link">Click Here</a> to log in.
</div>